"""base revision.

Revision ID: aef0008118ec
Revises: 
Create Date: 2024-05-11 19:51:03.869205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aef0008118ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('igdbgame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multiplayer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pc', sa.Boolean(), nullable=False),
    sa.Column('linux', sa.Boolean(), nullable=False),
    sa.Column('mac', sa.Boolean(), nullable=False),
    sa.Column('web_browser', sa.Boolean(), nullable=False),
    sa.Column('psp', sa.Boolean(), nullable=False),
    sa.Column('vital', sa.Boolean(), nullable=False),
    sa.Column('ps1', sa.Boolean(), nullable=False),
    sa.Column('ps2', sa.Boolean(), nullable=False),
    sa.Column('ps3', sa.Boolean(), nullable=False),
    sa.Column('ps4', sa.Boolean(), nullable=False),
    sa.Column('ps5', sa.Boolean(), nullable=False),
    sa.Column('xbox', sa.Boolean(), nullable=False),
    sa.Column('xbox_360', sa.Boolean(), nullable=False),
    sa.Column('xbox_one', sa.Boolean(), nullable=False),
    sa.Column('xbox_one_x', sa.Boolean(), nullable=False),
    sa.Column('nes', sa.Boolean(), nullable=False),
    sa.Column('super_nintendo', sa.Boolean(), nullable=False),
    sa.Column('n64', sa.Boolean(), nullable=False),
    sa.Column('game_boy', sa.Boolean(), nullable=False),
    sa.Column('game_boy_color', sa.Boolean(), nullable=False),
    sa.Column('game_boy_advance', sa.Boolean(), nullable=False),
    sa.Column('gamecube', sa.Boolean(), nullable=False),
    sa.Column('wii', sa.Boolean(), nullable=False),
    sa.Column('wii_u', sa.Boolean(), nullable=False),
    sa.Column('nintendo_switch', sa.Boolean(), nullable=False),
    sa.Column('nintendo_ds', sa.Boolean(), nullable=False),
    sa.Column('nintendo_3ds', sa.Boolean(), nullable=False),
    sa.Column('mobile', sa.Boolean(), nullable=False),
    sa.Column('ios', sa.Boolean(), nullable=False),
    sa.Column('android', sa.Boolean(), nullable=False),
    sa.Column('windows_mobile', sa.Boolean(), nullable=False),
    sa.Column('tg16', sa.Boolean(), nullable=False),
    sa.Column('tcd', sa.Boolean(), nullable=False),
    sa.Column('n_gage', sa.Boolean(), nullable=False),
    sa.Column('arcade', sa.Boolean(), nullable=False),
    sa.Column('sega_saturn', sa.Boolean(), nullable=False),
    sa.Column('sega_genesis', sa.Boolean(), nullable=False),
    sa.Column('dreamcast', sa.Boolean(), nullable=False),
    sa.Column('blackberry', sa.Boolean(), nullable=False),
    sa.Column('neo_geo', sa.Boolean(), nullable=False),
    sa.Column('neo_geo_pocket_color', sa.Boolean(), nullable=False),
    sa.Column('neo_geo_pocket', sa.Boolean(), nullable=False),
    sa.Column('famicom', sa.Boolean(), nullable=False),
    sa.Column('zeebo', sa.Boolean(), nullable=False),
    sa.Column('web_os', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('review_score', sa.Integer(), nullable=True),
    sa.Column('multiplayer_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['multiplayer_id'], ['multiplayer.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('platform')
    op.drop_table('multiplayer')
    op.drop_table('igdbgame')
    # ### end Alembic commands ###