# Generated by Django 4.2.4 on 2023-09-07 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multiplayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_count', models.IntegerField(db_column='multiplayer_player_count')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.BooleanField(db_column='platform_pc', default=False)),
                ('ps4', models.BooleanField(db_column='platform_ps4', default=False)),
                ('ps5', models.BooleanField(db_column='platform_ps5', default=False)),
                ('xbox_one_x', models.BooleanField(db_column='platform_xbox_one_x', default=False)),
                ('nintendo_switch', models.BooleanField(db_column='platform_nintendo_switch', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='game_title', max_length=50)),
                ('description', models.TextField(db_column='game_description')),
                ('release_date', models.DateField(db_column='game_release_date')),
                ('multiplayer', models.ForeignKey(db_column='game_multiplayer', on_delete=django.db.models.deletion.CASCADE, to='games.multiplayer')),
                ('platform', models.ForeignKey(db_column='game_platform', on_delete=django.db.models.deletion.CASCADE, to='games.platform')),
            ],
        ),
    ]
