# Generated by Django 4.2.4 on 2023-09-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='android',
            field=models.BooleanField(db_column='platform_android', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='arcade',
            field=models.BooleanField(db_column='platform_arcade', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='blackberry',
            field=models.BooleanField(db_column='platform_blackberry', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='dreamcast',
            field=models.BooleanField(db_column='platform_dreamcast', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='famicom',
            field=models.BooleanField(db_column='platform_famicom', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='game_boy',
            field=models.BooleanField(db_column='platform_game_boy', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='game_boy_advance',
            field=models.BooleanField(db_column='platform_game_boy_advance', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='game_boy_color',
            field=models.BooleanField(db_column='platform_game_boy_color', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='gamecube',
            field=models.BooleanField(db_column='platform_gamecube', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='ios',
            field=models.BooleanField(db_column='platform_ios', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='linux',
            field=models.BooleanField(db_column='platform_linux', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='mac',
            field=models.BooleanField(db_column='platform_mac', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='mobile',
            field=models.BooleanField(db_column='platform_mobile', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='n64',
            field=models.BooleanField(db_column='platform_64', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='n_gage',
            field=models.BooleanField(db_column='platform_n_gage', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='neo_geo',
            field=models.BooleanField(db_column='platform_neo_geo', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='neo_geo_pocket',
            field=models.BooleanField(db_column='platform_neo_geo_pocket', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='neo_geo_pocket_color',
            field=models.BooleanField(db_column='platform_neo_geo_pocket_color', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='nes',
            field=models.BooleanField(db_column='platform_nes', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='nintendo_3ds',
            field=models.BooleanField(db_column='platform_3ds', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='nintendo_ds',
            field=models.BooleanField(db_column='platform_nintendo_ds', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='ps1',
            field=models.BooleanField(db_column='platform_ps1', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='ps2',
            field=models.BooleanField(db_column='platform_ps2', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='ps3',
            field=models.BooleanField(db_column='platform_ps3', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='psp',
            field=models.BooleanField(db_column='platform_psp', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='sega_genesis',
            field=models.BooleanField(db_column='platform_sega_genesis', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='sega_saturn',
            field=models.BooleanField(db_column='platform_sega_saturn', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='super_nintendo',
            field=models.BooleanField(db_column='platform_super_nintendo', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='tcd',
            field=models.BooleanField(db_column='platform_tcd', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='tg16',
            field=models.BooleanField(db_column='platform_tg16', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='vita',
            field=models.BooleanField(db_column='platform_vita', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='web_browser',
            field=models.BooleanField(db_column='platform_web_browser', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='web_os',
            field=models.BooleanField(db_column='platform_web_os', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='wii',
            field=models.BooleanField(db_column='platform_wii', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='wii_u',
            field=models.BooleanField(db_column='platform_wii_u', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='windows_mobile',
            field=models.BooleanField(db_column='platform_windows_mobile', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='xbox',
            field=models.BooleanField(db_column='platform_xbox', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='xbox_360',
            field=models.BooleanField(db_column='platform_xbox_360', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='xbox_one',
            field=models.BooleanField(db_column='platform_xbox_one', default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='zeebo',
            field=models.BooleanField(db_column='platform_zeebo', default=False),
        ),
    ]
