# Generated by Django 4.2.4 on 2023-09-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_platform_android_platform_arcade_platform_blackberry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='review_score',
            field=models.IntegerField(db_column='game_review_score', default=-1),
            preserve_default=False,
        ),
    ]
