# Generated by Django 4.2.4 on 2023-09-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(db_column='game_description', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(db_column='game_release_date', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='review_score',
            field=models.IntegerField(db_column='game_review_score', null=True),
        ),
    ]
