# Generated by Django 4.2.4 on 2023-09-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_description_alter_game_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplayer',
            name='player_count',
            field=models.IntegerField(db_column='multiplayer_player_count', null=True),
        ),
    ]
