# Generated by Django 4.2.4 on 2023-11-07 02:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGDBGame',
            fields=[
                ('id', models.IntegerField(db_column='igdb_game_id', primary_key=True, serialize=False)),
                ('aggregated_rating', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_aggregated_rating', null=True), blank=True, null=True, size=None)),
                ('aggregated_rating_count', models.IntegerField(blank=True, db_column='igdb_game_aggregated_rating_count', null=True)),
                ('alternative_names', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_alternative_names', null=True), blank=True, null=True, size=None)),
                ('artworks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_artworks', null=True), blank=True, null=True, size=None)),
                ('bundles', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_bundles', null=True), blank=True, null=True, size=None)),
                ('category', models.IntegerField(blank=True, db_column='igdb_game_category', null=True)),
                ('checksum', models.UUIDField(blank=True, db_column='igdb_game_checksum', null=True)),
                ('collection', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_collection', null=True), blank=True, null=True, size=None)),
                ('cover', models.IntegerField(blank=True, db_column='igdb_game_cover', null=True)),
                ('created_at', models.IntegerField(blank=True, db_column='igdb_game_created_at', null=True)),
                ('dlcs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_dlcs', null=True), blank=True, null=True, size=None)),
                ('external_games', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_external_games', null=True), blank=True, null=True, size=None)),
                ('first_release_date', models.IntegerField(blank=True, db_column='igdb_game_first_release_date', null=True)),
                ('follows', models.IntegerField(blank=True, db_column='igdb_game_follows', null=True)),
                ('franchises', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_franchises', null=True), blank=True, null=True, size=None)),
                ('game_engines', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_game_engines', null=True), blank=True, null=True, size=None)),
                ('game_modes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_game_modes', null=True), blank=True, null=True, size=None)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_genres', null=True), blank=True, null=True, size=None)),
                ('hypes', models.IntegerField(blank=True, db_column='igdb_game_hypes', null=True)),
                ('involved_companies', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_involved_companies', null=True), blank=True, null=True, size=None)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_keywords', null=True), blank=True, null=True, size=None)),
                ('multiplayer_modes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_multiplayer_modes', null=True), blank=True, null=True, size=None)),
                ('name', models.CharField(blank=True, db_column='igdb_game_name', max_length=255, null=True)),
                ('parent_game', models.IntegerField(blank=True, db_column='igdb_game_parent_game', null=True)),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_platforms', null=True), blank=True, null=True, size=None)),
                ('player_perspectives', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_player_perspectives', null=True), blank=True, null=True, size=None)),
                ('rating', models.FloatField(blank=True, db_column='igdb_game_rating', null=True)),
                ('rating_count', models.IntegerField(blank=True, db_column='igdb_game_rating_count', null=True)),
                ('release_dates', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_release_dates', null=True), blank=True, null=True, size=None)),
                ('screenshots', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_screenshots', null=True), blank=True, null=True, size=None)),
                ('similar_games', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_similar_games', null=True), blank=True, null=True, size=None)),
                ('slug', models.SlugField(blank=True, db_column='igdb_game_slug', max_length=255, null=True)),
                ('standalone_expansions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_standalone_expansions', null=True), blank=True, null=True, size=None)),
                ('status', models.IntegerField(blank=True, db_column='igdb_game_status', null=True)),
                ('storylines', models.TextField(blank=True, db_column='igdb_game_storylines', null=True)),
                ('summary', models.TextField(blank=True, db_column='igdb_game_summary', null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_tags', null=True), blank=True, null=True, size=None)),
                ('themes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_themes', null=True), blank=True, null=True, size=None)),
                ('total_rating', models.FloatField(blank=True, db_column='igdb_game_total_rating', null=True)),
                ('total_rating_count', models.IntegerField(blank=True, db_column='igdb_game_total_rating_count', null=True)),
                ('updated_at', models.IntegerField(blank=True, db_column='igdb_game_updated_at', null=True)),
                ('url', models.URLField(blank=True, db_column='igdb_game_url', max_length=255, null=True)),
                ('version_parent', models.IntegerField(blank=True, db_column='igdb_game_version_parent', null=True)),
                ('version_title', models.CharField(blank=True, db_column='igdb_game_version_title', max_length=255, null=True)),
                ('videos', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_videos', null=True), blank=True, null=True, size=None)),
                ('websites', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_column='igdb_game_websites', null=True), blank=True, null=True, size=None)),
            ],
        ),
    ]
