services:
  backend:
    image: freakynoblegas/game-recommender:latest
    ports:
      - "8000:8000"
    networks:
      - game-recommender-network

  frontend:
    image: frontend/game-recommender:latest
    ports:
      - "5173:5173"
    networks:
      - game-recommender-network

networks:
  game-recommender-network:
    driver: bridge
