services:
  frontend:
    image: frontend/game-recommender:latest
    ports:
      - "5173:5173"
    networks:
      - default

  backend:
    image: freakynoblegas/game-recommender:latest
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - default
networks:
  default:
    driver: bridge
